export const reportIds = [
  'affected-urls',
  'ai-readiness',
  'ai-referrals',
  'audit-page',
  'audit-urls',
  'cannibal',
  'community-intent',
  'compare-crawl-reports',
  'content-optimization',
  'crawl-diff',
  'crawl-site',
  'ctr-underperformers',
  'decaying',
  'diagnose-property',
  'doctor',
  'entity-readiness',
  'explain-issue',
  'geo-gaps',
  'get-crawl-report',
  'index-coverage-plan',
  'index-monitor',
  'index-watch',
  'internal-links',
  'link-recover',
  'list-crawl-reports',
  'list-rules',
  'llms-txt-audit',
  'llms-txt-generate',
  'measure-change',
  'monthly-report',
  'okf-build',
  'okf-validate',
  'page-opportunities',
  'performance-audit',
  'pseo-audit',
  'query-cluster',
  'quick-wins',
  'redirect-trace',
  'report-narrative',
  'second-page',
  'segment-impact',
  'striking-distance',
  'to-ai-query',
  'top-fixes',
  'traffic-anomaly',
  'update-correlate',
  'workflow-diagnose-property',
  'workflow-monthly-report',
  'workflow-refresh-priorities',
  'workflow-technical-watch',
  'workflow-update-postmortem',
]

export const legacyReportAliases = {
  'broad-seo-report': 'diagnose-property',
  cannibalisation: 'cannibal',
  'change-log': 'measure-change',
  'content-groups': '/docs/cli',
  'decaying-pages': 'decaying',
  'ga4-report': '/docs/google',
  'generate-llms-txt': 'llms-txt-generate',
  'index-coverage': 'index-monitor',
  'index-plan': 'index-coverage-plan',
  'knowledge-export': 'okf-build',
  'link-recovery': 'link-recover',
  'narrative-report': 'report-narrative',
  'okf-export': 'okf-build',
  'query-clusters': 'query-cluster',
  'refresh-priorities': 'workflow-refresh-priorities',
  'search-console-actions': 'workflow-diagnose-property',
  'search-console-query': '/docs/google',
  'search-status-updates': 'update-correlate',
  'seo-tests': 'measure-change',
  'seo-to-ai-query': 'to-ai-query',
  'site-crawl': 'crawl-site',
  'technical-watch': 'workflow-technical-watch',
  'update-postmortem': 'workflow-update-postmortem',
  'url-inspection': '/docs/google',
}
