export const reportIds = [
  'affected-urls',
  'agent-readiness',
  'ai-readiness',
  'ai-referrals',
  'ai-search-scorecard',
  'audit-page',
  'audit-urls',
  'bing-webmaster-overview',
  'cannibalisation',
  'community-intent',
  'compare-crawls',
  'competitor-keyword-gap',
  'content-optimization',
  'crawl-diff',
  'site-crawl',
  'ctr-underperformers',
  'decaying-pages',
  'domain-overview',
  'setup-check',
  'entity-readiness',
  'explain-crawl-issue',
  'geo-gaps',
  'crawl-report',
  'index-coverage',
  'index-coverage-plan',
  'index-monitor',
  'index-watch',
  'internal-links',
  'keyword-metrics',
  'keyword-opportunities',
  'keyword-research',
  'saved-keywords',
  'link-evidence',
  'server-log-analysis',
  'link-recovery',
  'crawl-history',
  'crawler-rules',
  'llms-txt-audit',
  'generate-llms-txt',
  'measure-change',
  'monthly-report',
  'okf-build',
  'okf-validate',
  'page-opportunities',
  'performance-audit',
  'pseo-audit',
  'pseo-opportunities',
  'query-clusters',
  'quick-wins',
  'rank-tracking',
  'ranked-keywords',
  'ranking-pages',
  'redirect-trace',
  'narrative-report',
  'second-page',
  'segment-impact',
  'serp-results',
  'serp-competitors',
  'striking-distance',
  'seo-to-ai-query',
  'top-fixes',
  'traffic-anomaly',
  'update-correlation',
  'search-performance-overview',
  'monthly-action-plan',
  'refresh-priorities',
  'technical-watch',
  'update-postmortem',
]

export const reportSlugs = {
  'index-coverage-plan': 'index-plan',
}

export const legacyReportAliases = {
  'broad-seo-report': 'search-performance-overview',
  'change-log': 'measure-change',
  'content-groups': '/docs/cli',
  'knowledge-export': 'okf-build',
  'okf-export': 'okf-build',
  'search-console-actions': 'refresh-priorities',
  'search-console-query': '/docs/google',
  'search-status-updates': '/docs/google',
  'seo-tests': 'measure-change',
  'url-inspection': '/docs/google',
}
