/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: 42847a611234dc3d0404d63aea12e0ad)
interface __BaseEnv_Env {
	TELEMETRY_DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
