/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: 29deaa75b850804f5c9d0f471c4b543d)
interface __BaseEnv_Env {
	TELEMETRY_DB: D1Database;
	TOOL_CLIENT_RATE_LIMITER: RateLimit;
	TOOL_ROUTE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	LOCAL_TOOL_PREVIEW: "false";
	AHREFS_DAILY_PROVIDER_LIMIT: "500";
	DATAFORSEO_SPAM_DAILY_PROVIDER_LIMIT: "100";
	DATAFORSEO_TRAFFIC_DAILY_PROVIDER_LIMIT: "10";
	TURNSTILE_SECRET_KEY: string;
	TOOL_QUOTA_HASH_KEY: string;
	AHREFS_API_KEY: string;
	DATAFORSEO_LOGIN: string;
	DATAFORSEO_PASSWORD: string;
	PAID_TOOL_GUARD: DurableObjectNamespace<import("./index").PaidToolGuard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "PaidToolGuard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LOCAL_TOOL_PREVIEW" | "AHREFS_DAILY_PROVIDER_LIMIT" | "DATAFORSEO_SPAM_DAILY_PROVIDER_LIMIT" | "DATAFORSEO_TRAFFIC_DAILY_PROVIDER_LIMIT" | "TURNSTILE_SECRET_KEY" | "TOOL_QUOTA_HASH_KEY" | "AHREFS_API_KEY" | "DATAFORSEO_LOGIN" | "DATAFORSEO_PASSWORD">> {}
}
