import { defineConfig } from 'tsdown'

export default defineConfig([
  {
    entry: ['src/index.ts'],
    format: ['esm'],
    platform: 'node',
    target: 'es2022',
    fixedExtension: false,
    dts: true,
    sourcemap: true,
    clean: true,
  },
  {
    entry: [
      'src/ai-opportunity-tools.ts',
      'src/crawler-tools.ts',
      'src/discovery-tools.ts',
      'src/diagnosis-tools.ts',
      'src/experiment-tools.ts',
      'src/fetch-rate.ts',
      'src/input-schemas.ts',
      'src/local-search-tools.ts',
      'src/monitoring-tools.ts',
      'src/opportunity-tools.ts',
      'src/pseo-tools.ts',
      'src/report-registry.ts',
      'src/report-options.ts',
      'src/report-tools.ts',
      'src/report-tools/*.ts',
      'src/reports.ts',
      'src/tool-result.ts',
      'src/workflow-tools.ts',
      'src/**/*.test.ts',
    ],
    format: ['esm'],
    platform: 'node',
    target: 'es2022',
    fixedExtension: false,
    unbundle: true,
    dts: false,
    sourcemap: true,
    clean: false,
  },
])
